return {
	"AstroNvim/astrocore",
	opts = {
		features = {
			large_buf = { size = 1024 * 500, lines = 10000 },
			autopairs = true,
			cmp = true,
			diagnostics_mode = 3,
			highlighturl = true,
			notifications = true,
		},
		diagnostics = {
			virtual_text = true,
			underline = true,
		},
		options = {
			opt = {
				updatetime = 100,
				title = true,
				splitbelow = true,
				splitright = true,
				diffopt = vim.opt.diffopt + "vertical",
				linebreak = true,
				cursorline = true,
				breakindent = true,
				list = true,
				listchars = {
					tab = "󰌒",
					trail = "·",
					nbsp = "␣",
					extends = "…",
					precedes = "…",
				},
				relativenumber = false,
				number = true,
				spell = true,
				signcolumn = "auto",
				wrap = true,
				tabstop = 4,
			},
			g = {},
		},
		mappings = {},
		autocmd = {},
	},
}
