[edit]
command = "nvim"

[diff]
exclude = ["scripts"]

[merge]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[status]
exclude = ["scripts"]

[data]
name = "Fábio Luciano"
email = "fabio@naoimporta.com"
github_user = "fabioluciano"
weather_city = "Brasilia,Brazil"
